version: '3'
services:
  async_api:
    ports:
      - "8100:8000"
  functional_tests:
    build: ./tests/functional
    env_file:
      - .env.docker
    networks:
      - async_api_network
  elastic:
    ports:
      - "9200:9200"
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
