version: '3'
services:
  async_api:
    build: ./src
    env_file:
      - .env.docker
    networks:
      - async_api_network

  elastic:
    image: docker.io/elastic/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    networks:
      - async_api_network

  redis:
    image: redis
    networks:
      - async_api_network

  postgres:
    image: postgres:13
    env_file:
      - .env.docker
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    networks:
      - async_api_network

  etl:
    image: ghcr.io/zhovtanovskaya/new_admin_panel_sprint_3_etl:v0.1
    env_file:
      - .env.docker
    networks:
      - async_api_network

networks:
  async_api_network:
    driver: bridge

volumes:
  static_volume:
